version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: >
      sh -c "
        echo '🚀 Ждём базу данных...' &&
        until mysqladmin ping -h db --silent; do
          echo '⏳ Ожидание...'; sleep 2;
        done &&
        echo '✅ БД готова!' &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: db
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: secret123

volumes:
  mysql_data:
  