# Generated by Django 5.1.5 on 2025-03-05 13:36

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodel',
            options={'verbose_name': 'Fake', 'verbose_name_plural': 'Fake`s'},
        ),
        migrations.AlterField(
            model_name='fakemodel',
            name='email',
            field=models.EmailField(db_column='gmail', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='fakemodel',
            name='img',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='fake/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='fakemodel',
            name='text',
            field=models.TextField(db_column='text', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todomodeltranslation',
            name='description',
            field=ckeditor.fields.RichTextField(db_column='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='todomodeltranslation',
            name='is_active',
            field=models.BooleanField(db_column='active', default=False, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='todomodeltranslation',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='todomodeltranslation',
            name='title',
            field=models.CharField(db_column='title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterModelTable(
            name='fakemodel',
            table='Fake model',
        ),
        migrations.AlterModelTable(
            name='todomodel',
            table='todo',
        ),
        migrations.AlterModelTable(
            name='todomodeltranslation',
            table='todo_translation',
        ),
    ]
