# Generated by Django 5.1.5 on 2025-03-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_fakemodel_options_alter_fakemodel_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fakemodel',
            table='Fake',
        ),
    ]
